global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cloudflow'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        # host.docker.internal = your laptop's IP as seen from inside Docker