apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: cloudflow
spec:
  accessModes:
    - ReadWriteOnce       # One pod can mount this at a time
  resources:
    requests:
      storage: 2Gi